### ISSUE TITLE
Handling in-line errors

### ISSUE THREAD

**Issue by mtHuberty** [ohanedan/Lowlight-Go-Errors#2]
Great plugin! 

It looks like it doesn't catch the inline err-handling syntax like so: 
![image](https://user-images.githubusercontent.com/31088971/106025365-4a1d7880-608e-11eb-91ba-26182d8e75a9.png)

I could take a swing at fixing it for you if you're open to PRs. Let me know!

**Comment by ohanedan** [comment]
You can! I will accept the PR after reviewing. I would appreciate it if you could also add a setting to on/off for inline errors.

**Comment by mtHuberty** [comment]
I've got 0 experience developing VSCode extensions, so it'll take me a little time to orient myself but your src code is pretty clear and not super intimidating so I'm looking forward to working on it when I get some spare time soon.

**Comment by ohanedan** [comment]
>= 1.3.0
thanks @facundoarca
